<?php defined('BILLINGMASTER') or die;

$folders = array(
    array('/images/course'),
    array('/images/course/category'),
    array('/images/forvideo'),
    array('/images/lessons'),
    array('/images/post'),
    array('/images/post/cover'),
    array('/images/product'),
    array('/images/reviews'),
    array('/images/socicons'),
    array('/images/thumbs'),
    array('/images/thumbs/course'),
    array('/images/thumbs/course/category'),
    array('/images/thumbs/lessons'),
    array('/images/thumbs/post'),
    array('/images/thumbs/post/cover'),
    array('/images/thumbs/product'),
    array('/images/thumbs/reviews'),
    array('/images/thumbs/thumbs'),
    array('/images/training'),
    array('/images/training/lessons'),
    array('/images/training/sections'),
    array('/load'),
    array('/load/hometask'),
    array('/load/hometask/lessons'),
    array('/load/hometask/lessons/20'),
    array('/load/hometask/lessons/20/user'),
    array('/load/thumbs'),
    array('/load/thumbs/course'),
    array('/load/thumbs/course/category'),
    array('/load/thumbs/forvideo'),
    array('/load/thumbs/lessons'),
    array('/load/thumbs/product'),
    array('/load/thumbs/socicons'),
    array('/load/thumbs/thumbs'),
    array('/load/thumbs/training'),
    array('/load/thumbs/training/lessons'),
    array('/load/training'),
    array('/load/training/lessons'),
    array('/load/training/lessons/21'),
    array('/load/training/lessons/34'),
    array('/load/training/lessons/36'),
    array('/load/training/lessons/43'),
    array('/template/admin/images/payments'),
);

$files = array(
    array('/images/3 (1).jpg', 'images/3 (1).jpg'),
    array('/images/773657_37780-Sarah1-e1555765907998.jpg', 'images/773657_37780-Sarah1-e1555765907998.jpg'),
    array('/images/Screenshot_20200220-013947_AliRadar.jpg', 'images/Screenshot_20200220-013947_AliRadar.jpg'),
    array('/images/aleksandr (1).png', 'images/aleksandr (1).png'),
    array('/images/alexandrkurteev_2.png', 'images/alexandrkurteev_2.png'),
    array('/images/blog-hero.jpg', 'images/blog-hero.jpg'),
    array('/images/cheboksar.jpg', 'images/cheboksar.jpg'),
    array('/images/course/1k.jpg', 'images/course/1k.jpg'),
    array('/images/course/2k.jpg', 'images/course/2k.jpg'),
    array('/images/course/3k.jpg', 'images/course/3k.jpg'),
    array('/images/course/54.jpg', 'images/course/54.jpg'),
    array('/images/course/Kak-nachat-begat-polnoe-rukovodstvo-dlya-novichkov_1579903200-1140x570.jpg', 'images/course/Kak-nachat-begat-polnoe-rukovodstvo-dlya-novichkov_1579903200-1140x570.jpg'),
    array('/images/course/category/1.jpg', 'images/course/category/1.jpg'),
    array('/images/course/category/Razminka-pered-begom.jpg', 'images/course/category/Razminka-pered-begom.jpg'),
    array('/images/course/category/bonusesmain.jpg', 'images/course/category/bonusesmain.jpg'),
    array('/images/course/category/course.jpg', 'images/course/category/course.jpg'),
    array('/images/course/lessonsystem (1).jpg', 'images/course/lessonsystem (1).jpg'),
    array('/images/course/triatlon.jpg', 'images/course/triatlon.jpg'),
    array('/images/course/triatlon1.jpg', 'images/course/triatlon1.jpg'),
    array('/images/down-arrow (1).png', 'images/down-arrow (1).png'),
    array('/images/down-arrow.png', 'images/down-arrow.png'),
    array('/images/downloadfile.png', 'images/downloadfile.png'),
    array('/images/forvideo/integration.jpg', 'images/forvideo/integration.jpg'),
    array('/images/forvideo/intro1.jpg', 'images/forvideo/intro1.jpg'),
    array('/images/forvideo/intro2.jpg', 'images/forvideo/intro2.jpg'),
    array('/images/forvideo/intro3.jpg', 'images/forvideo/intro3.jpg'),
    array('/images/forvideo/intro5.jpg', 'images/forvideo/intro5.jpg'),
    array('/images/forvideo/membership1-1.jpg', 'images/forvideo/membership1-1.jpg'),
    array('/images/forvideo/membership1.jpg', 'images/forvideo/membership1.jpg'),
    array('/images/forvideo/membership2.jpg', 'images/forvideo/membership2.jpg'),
    array('/images/forvideo/membership3.jpg', 'images/forvideo/membership3.jpg'),
    array('/images/forvideo/membership4.jpg', 'images/forvideo/membership4.jpg'),
    array('/images/forvideo/membership5.jpg', 'images/forvideo/membership5.jpg'),
    array('/images/forvideo/partner1-1.jpg', 'images/forvideo/partner1-1.jpg'),
    array('/images/forvideo/partner1.jpg', 'images/forvideo/partner1.jpg'),
    array('/images/forvideo/partner2.jpg', 'images/forvideo/partner2.jpg'),
    array('/images/forvideo/partner3.jpg', 'images/forvideo/partner3.jpg'),
    array('/images/forvideo/partner4.jpg', 'images/forvideo/partner4.jpg'),
    array('/images/forvideo/partner5.jpg', 'images/forvideo/partner5.jpg'),
    array('/images/forvideo/sale1.jpg', 'images/forvideo/sale1.jpg'),
    array('/images/forvideo/sale2.jpg', 'images/forvideo/sale2.jpg'),
    array('/images/forvideo/sale3.jpg', 'images/forvideo/sale3.jpg'),
    array('/images/forvideo/sale4.jpg', 'images/forvideo/sale4.jpg'),
    array('/images/forvideo/sale5.jpg', 'images/forvideo/sale5.jpg'),
    array('/images/forvideo/sale6.jpg', 'images/forvideo/sale6.jpg'),
    array('/images/forvideo/sale7.jpg', 'images/forvideo/sale7.jpg'),
    array('/images/forvideo/site1.jpg', 'images/forvideo/site1.jpg'),
    array('/images/forvideo/site10.jpg', 'images/forvideo/site10.jpg'),
    array('/images/forvideo/site2.jpg', 'images/forvideo/site2.jpg'),
    array('/images/forvideo/site3.jpg', 'images/forvideo/site3.jpg'),
    array('/images/forvideo/site4.jpg', 'images/forvideo/site4.jpg'),
    array('/images/forvideo/site5.jpg', 'images/forvideo/site5.jpg'),
    array('/images/forvideo/site6.jpg', 'images/forvideo/site6.jpg'),
    array('/images/forvideo/site7.jpg', 'images/forvideo/site7.jpg'),
    array('/images/forvideo/site8.jpg', 'images/forvideo/site8.jpg'),
    array('/images/forvideo/site9.jpg', 'images/forvideo/site9.jpg'),
    array('/images/forvideo/user1.jpg', 'images/forvideo/user1.jpg'),
    array('/images/forvideo/user2.jpg', 'images/forvideo/user2.jpg'),
    array('/images/forvideo/user3.jpg', 'images/forvideo/user3.jpg'),
    array('/images/forvideo/user4.jpg', 'images/forvideo/user4.jpg'),
    array('/images/forvideo/user5.jpg', 'images/forvideo/user5.jpg'),
    array('/images/hero (1).jpg', 'images/hero (1).jpg'),
    array('/images/hero.jpg', 'images/hero.jpg'),
    array('/images/lessons/1-1.jpg', 'images/lessons/1-1.jpg'),
    array('/images/lessons/1.jpg', 'images/lessons/1.jpg'),
    array('/images/lessons/10.jpg', 'images/lessons/10.jpg'),
    array('/images/lessons/11.jpg', 'images/lessons/11.jpg'),
    array('/images/lessons/1l.jpg', 'images/lessons/1l.jpg'),
    array('/images/lessons/2.jpg', 'images/lessons/2.jpg'),
    array('/images/lessons/3.jpg', 'images/lessons/3.jpg'),
    array('/images/lessons/4.jpg', 'images/lessons/4.jpg'),
    array('/images/lessons/5.jpg', 'images/lessons/5.jpg'),
    array('/images/lessons/6.jpg', 'images/lessons/6.jpg'),
    array('/images/lessons/7.jpg', 'images/lessons/7.jpg'),
    array('/images/lessons/8.jpg', 'images/lessons/8.jpg'),
    array('/images/lessons/9.jpg', 'images/lessons/9.jpg'),
    array('/images/lessons/motivation.jpg', 'images/lessons/motivation.jpg'),
    array('/images/lessons/runner.jpg', 'images/lessons/runner.jpg'),
    array('/images/lessons/swim.jpg', 'images/lessons/swim.jpg'),
    array('/images/lessons/velosiped.jpg', 'images/lessons/velosiped.jpg'),
    array('/images/logo-maraphonec-copy.png', 'images/logo-maraphonec-copy.png'),
    array('/images/logo-sport.png', 'images/logo-sport.png'),
    array('/images/logo2.png', 'images/logo2.png'),
    array('/images/logo3.png', 'images/logo3.png'),
    array('/images/morning.jpg', 'images/morning.jpg'),
    array('/images/olega.png', 'images/olega.png'),
    array('/images/post/cover/-л-эT·T-эT·----¬ё¤+Lёл-.jpg', 'images/post/cover/-л-эT·T-эT·----¬ё¤+Lёл-.jpg'),
    array('/images/post/cover/Razminka-pered-begom.jpg', 'images/post/cover/Razminka-pered-begom.jpg'),
    array('/images/post/cover/begunya-v-naushnikah.jpg', 'images/post/cover/begunya-v-naushnikah.jpg'),
    array('/images/post/cover/breath.jpg', 'images/post/cover/breath.jpg'),
    array('/images/post/cover/muzhchina-bezhit-po-doroge.jpg', 'images/post/cover/muzhchina-bezhit-po-doroge.jpg'),
    array('/images/post/cover/puls-vo-vremya-bega-800x533.jpg', 'images/post/cover/puls-vo-vremya-bega-800x533.jpg'),
    array('/images/post/cover/pulse.jpg', 'images/post/cover/pulse.jpg'),
    array('/images/post/cover/razmer-bootstrap[1].png', 'images/post/cover/razmer-bootstrap[1].png'),
    array('/images/post/cover/razminka.jpg', 'images/post/cover/razminka.jpg'),
    array('/images/post/cover/rule of run.jpg', 'images/post/cover/rule of run.jpg'),
    array('/images/post/cover/run with lidjard.jpg', 'images/post/cover/run with lidjard.jpg'),
    array('/images/post/cover/run.jpg', 'images/post/cover/run.jpg'),
    array('/images/post/cover/scale_2400.webp', 'images/post/cover/scale_2400.webp'),
    array('/images/post/cover/sport.jpg', 'images/post/cover/sport.jpg'),
    array('/images/post/cover/vds-hosting[1].png', 'images/post/cover/vds-hosting[1].png'),
    array('/images/post/cover/widget-vk-joomla[1].jpg', 'images/post/cover/widget-vk-joomla[1].jpg'),
    array('/images/post/cover/zabeg2020.jpg', 'images/post/cover/zabeg2020.jpg'),
    array('/images/post-002.png', 'images/post-002.png'),
    array('/images/product/108411307_w640_h640_turnik-atlet-3[1].jpg', 'images/product/108411307_w640_h640_turnik-atlet-3[1].jpg'),
    array('/images/product/1k.jpg', 'images/product/1k.jpg'),
    array('/images/product/3k.jpg', 'images/product/3k.jpg'),
    array('/images/product/90.jpg', 'images/product/90.jpg'),
    array('/images/product/bike.jpg', 'images/product/bike.jpg'),
    array('/images/product/couch.png', 'images/product/couch.png'),
    array('/images/product/maraphon.jpg', 'images/product/maraphon.jpg'),
    array('/images/product/nike.jpg', 'images/product/nike.jpg'),
    array('/images/product/product-marafon.jpg', 'images/product/product-marafon.jpg'),
    array('/images/product/stand.jpg', 'images/product/stand.jpg'),
    array('/images/product/startrun.jpg', 'images/product/startrun.jpg'),
    array('/images/product/swim.jpg', 'images/product/swim.jpg'),
    array('/images/product/tri2.jpg', 'images/product/tri2.jpg'),
    array('/images/product/triathlonpremium.png', 'images/product/triathlonpremium.png'),
    array('/images/product/triathlonstand.png', 'images/product/triathlonstand.png'),
    array('/images/product/triatlon-product.jpg', 'images/product/triatlon-product.jpg'),
    array('/images/product/tristand.png', 'images/product/tristand.png'),
    array('/images/product/vip.png', 'images/product/vip.png'),
    array('/images/product/vip2-copy.png', 'images/product/vip2-copy.png'),
    array('/images/product/vip2.png', 'images/product/vip2.png'),
    array('/images/reviews/dd53196c6d33a0a1349a42defa6e831f.jpeg', 'images/reviews/dd53196c6d33a0a1349a42defa6e831f.jpeg'),
    array('/images/reviews/ec283dab9c8ffedc5f05d5aee5aa604d.jpeg', 'images/reviews/ec283dab9c8ffedc5f05d5aee5aa604d.jpeg'),
    array('/images/reviews/img-rev-1.jpg', 'images/reviews/img-rev-1.jpg'),
    array('/images/reviews/img-rev-2.jpg', 'images/reviews/img-rev-2.jpg'),
    array('/images/reviews/img-rev-3.jpg', 'images/reviews/img-rev-3.jpg'),
    array('/images/socicons/facebook.png', 'images/socicons/facebook.png'),
    array('/images/socicons/instagram.png', 'images/socicons/instagram.png'),
    array('/images/socicons/telegram.png', 'images/socicons/telegram.png'),
    array('/images/socicons/vk 1.png', 'images/socicons/vk 1.png'),
    array('/images/streaks.png', 'images/streaks.png'),
    array('/images/thumbs/23-Defenders_Day-23.jpg', 'images/thumbs/23-Defenders_Day-23.jpg'),
    array('/images/thumbs/Logosports.png', 'images/thumbs/Logosports.png'),
    array('/images/thumbs/Screenshot_20200220-013947_AliRadar.jpg', 'images/thumbs/Screenshot_20200220-013947_AliRadar.jpg'),
    array('/images/thumbs/Shika.png', 'images/thumbs/Shika.png'),
    array('/images/thumbs/aleksandr (1).png', 'images/thumbs/aleksandr (1).png'),
    array('/images/thumbs/alexandrkurteev_2.png', 'images/thumbs/alexandrkurteev_2.png'),
    array('/images/thumbs/blog-hero.jpg', 'images/thumbs/blog-hero.jpg'),
    array('/images/thumbs/cheboksar.jpg', 'images/thumbs/cheboksar.jpg'),
    array('/images/thumbs/course/1k.jpg', 'images/thumbs/course/1k.jpg'),
    array('/images/thumbs/course/2k.jpg', 'images/thumbs/course/2k.jpg'),
    array('/images/thumbs/course/3k.jpg', 'images/thumbs/course/3k.jpg'),
    array('/images/thumbs/course/54.jpg', 'images/thumbs/course/54.jpg'),
    array('/images/thumbs/course/Kak-nachat-begat-polnoe-rukovodstvo-dlya-novichkov_1579903200-1140x570.jpg', 'images/thumbs/course/Kak-nachat-begat-polnoe-rukovodstvo-dlya-novichkov_1579903200-1140x570.jpg'),
    array('/images/thumbs/course/category/1.jpg', 'images/thumbs/course/category/1.jpg'),
    array('/images/thumbs/course/category/Razminka-pered-begom.jpg', 'images/thumbs/course/category/Razminka-pered-begom.jpg'),
    array('/images/thumbs/course/category/bonusesmain.jpg', 'images/thumbs/course/category/bonusesmain.jpg'),
    array('/images/thumbs/course/category/course.jpg', 'images/thumbs/course/category/course.jpg'),
    array('/images/thumbs/course/joomla-3-500.png', 'images/thumbs/course/joomla-3-500.png'),
    array('/images/thumbs/course/triatlon.jpg', 'images/thumbs/course/triatlon.jpg'),
    array('/images/thumbs/course/triatlon1.jpg', 'images/thumbs/course/triatlon1.jpg'),
    array('/images/thumbs/female_avatar.png', 'images/thumbs/female_avatar.png'),
    array('/images/thumbs/hero (1).jpg', 'images/thumbs/hero (1).jpg'),
    array('/images/thumbs/hero.jpg', 'images/thumbs/hero.jpg'),
    array('/images/thumbs/hero1.jpg', 'images/thumbs/hero1.jpg'),
    array('/images/thumbs/keit.jpg', 'images/thumbs/keit.jpg'),
    array('/images/thumbs/lessons/j3-detail.png', 'images/thumbs/lessons/j3-detail.png'),
    array('/images/thumbs/lessons/kirov.jpg', 'images/thumbs/lessons/kirov.jpg'),
    array('/images/thumbs/lessons/kurs-2.jpg', 'images/thumbs/lessons/kurs-2.jpg'),
    array('/images/thumbs/lessons/yoshka.jpg', 'images/thumbs/lessons/yoshka.jpg'),
    array('/images/thumbs/logo-sport.png', 'images/thumbs/logo-sport.png'),
    array('/images/thumbs/logo2.png', 'images/thumbs/logo2.png'),
    array('/images/thumbs/logo3.png', 'images/thumbs/logo3.png'),
    array('/images/thumbs/noavatar.png', 'images/thumbs/noavatar.png'),
    array('/images/thumbs/olega.png', 'images/thumbs/olega.png'),
    array('/images/thumbs/pavel.jpg', 'images/thumbs/pavel.jpg'),
    array('/images/thumbs/post/cover/razmer-bootstrap[1].png', 'images/thumbs/post/cover/razmer-bootstrap[1].png'),
    array('/images/thumbs/post/cover/vds-hosting[1].png', 'images/thumbs/post/cover/vds-hosting[1].png'),
    array('/images/thumbs/post/cover/widget-vk-joomla[1].jpg', 'images/thumbs/post/cover/widget-vk-joomla[1].jpg'),
    array('/images/thumbs/post-002.png', 'images/thumbs/post-002.png'),
    array('/images/thumbs/product/108411307_w640_h640_turnik-atlet-3[1].jpg', 'images/thumbs/product/108411307_w640_h640_turnik-atlet-3[1].jpg'),
    array('/images/thumbs/product/1k.jpg', 'images/thumbs/product/1k.jpg'),
    array('/images/thumbs/product/33339_5c7531b50b46f4.40591348.jpg', 'images/thumbs/product/33339_5c7531b50b46f4.40591348.jpg'),
    array('/images/thumbs/product/3k.jpg', 'images/thumbs/product/3k.jpg'),
    array('/images/thumbs/product/90.jpg', 'images/thumbs/product/90.jpg'),
    array('/images/thumbs/product/SEO-secrets-specialist-500.png', 'images/thumbs/product/SEO-secrets-specialist-500.png'),
    array('/images/thumbs/product/SEO-text-350.png', 'images/thumbs/product/SEO-text-350.png'),
    array('/images/thumbs/product/adaptive-html5-css3-cover-500.png', 'images/thumbs/product/adaptive-html5-css3-cover-500.png'),
    array('/images/thumbs/product/html-css-cover-450.png', 'images/thumbs/product/html-css-cover-450.png'),
    array('/images/thumbs/product/joomla-3-500.png', 'images/thumbs/product/joomla-3-500.png'),
    array('/images/thumbs/product/maraphon.jpg', 'images/thumbs/product/maraphon.jpg'),
    array('/images/thumbs/product/nike.jpg', 'images/thumbs/product/nike.jpg'),
    array('/images/thumbs/product/product-marafon.jpg', 'images/thumbs/product/product-marafon.jpg'),
    array('/images/thumbs/product/shop_cover_500.png', 'images/thumbs/product/shop_cover_500.png'),
    array('/images/thumbs/product/sposob-700opt.png', 'images/thumbs/product/sposob-700opt.png'),
    array('/images/thumbs/product/startrun.jpg', 'images/thumbs/product/startrun.jpg'),
    array('/images/thumbs/product/t2.jpg', 'images/thumbs/product/t2.jpg'),
    array('/images/thumbs/product/triatlon-product.jpg', 'images/thumbs/product/triatlon-product.jpg'),
    array('/images/thumbs/product/verstka-cover-500.png', 'images/thumbs/product/verstka-cover-500.png'),
    array('/images/thumbs/reviews/dd53196c6d33a0a1349a42defa6e831f.jpeg', 'images/thumbs/reviews/dd53196c6d33a0a1349a42defa6e831f.jpeg'),
    array('/images/thumbs/reviews/ec283dab9c8ffedc5f05d5aee5aa604d.jpeg', 'images/thumbs/reviews/ec283dab9c8ffedc5f05d5aee5aa604d.jpeg'),
    array('/images/thumbs/sila_metoda.jpg', 'images/thumbs/sila_metoda.jpg'),
    array('/images/thumbs/tema-T¦м¬о-э-л·.jpg', 'images/thumbs/tema-T¦м¬о-э-л·.jpg'),
    array('/images/thumbs/thumbs/23-Defenders_Day-23.jpg', 'images/thumbs/thumbs/23-Defenders_Day-23.jpg'),
    array('/images/thumbs/thumbs/Logosports.png', 'images/thumbs/thumbs/Logosports.png'),
    array('/images/thumbs/thumbs/Screenshot_20200220-013947_AliRadar.jpg', 'images/thumbs/thumbs/Screenshot_20200220-013947_AliRadar.jpg'),
    array('/images/thumbs/thumbs/Shika.png', 'images/thumbs/thumbs/Shika.png'),
    array('/images/thumbs/thumbs/aleksandr (1).png', 'images/thumbs/thumbs/aleksandr (1).png'),
    array('/images/thumbs/thumbs/alexandrkurteev_2.png', 'images/thumbs/thumbs/alexandrkurteev_2.png'),
    array('/images/thumbs/thumbs/blog-hero.jpg', 'images/thumbs/thumbs/blog-hero.jpg'),
    array('/images/thumbs/thumbs/cheboksar.jpg', 'images/thumbs/thumbs/cheboksar.jpg'),
    array('/images/thumbs/thumbs/hero (1).jpg', 'images/thumbs/thumbs/hero (1).jpg'),
    array('/images/thumbs/thumbs/hero.jpg', 'images/thumbs/thumbs/hero.jpg'),
    array('/images/thumbs/thumbs/hero1.jpg', 'images/thumbs/thumbs/hero1.jpg'),
    array('/images/thumbs/thumbs/keit.jpg', 'images/thumbs/thumbs/keit.jpg'),
    array('/images/thumbs/thumbs/kirov.jpg', 'images/thumbs/thumbs/kirov.jpg'),
    array('/images/thumbs/thumbs/logo-sport.png', 'images/thumbs/thumbs/logo-sport.png'),
    array('/images/thumbs/thumbs/logo2.png', 'images/thumbs/thumbs/logo2.png'),
    array('/images/thumbs/thumbs/logo3.png', 'images/thumbs/thumbs/logo3.png'),
    array('/images/thumbs/thumbs/noavatar.png', 'images/thumbs/thumbs/noavatar.png'),
    array('/images/thumbs/thumbs/olega.png', 'images/thumbs/thumbs/olega.png'),
    array('/images/thumbs/thumbs/sila_metoda.jpg', 'images/thumbs/thumbs/sila_metoda.jpg'),
    array('/images/thumbs/thumbs/witcher.jpg', 'images/thumbs/thumbs/witcher.jpg'),
    array('/images/thumbs/tr.jpg', 'images/thumbs/tr.jpg'),
    array('/images/thumbs/witcher.jpg', 'images/thumbs/witcher.jpg'),
    array('/images/tracker.png', 'images/tracker.png'),
    array('/images/training/IM-smart-programs-header.jpg', 'images/training/IM-smart-programs-header.jpg'),
    array('/images/training/bike.jpg', 'images/training/bike.jpg'),
    array('/images/training/lessons/1-160px.jpg', 'images/training/lessons/1-160px.jpg'),
    array('/images/training/lessons/1-2-160px.jpg', 'images/training/lessons/1-2-160px.jpg'),
    array('/images/training/lessons/1-2.jpg', 'images/training/lessons/1-2.jpg'),
    array('/images/training/lessons/1-copy-160px.jpg', 'images/training/lessons/1-copy-160px.jpg'),
    array('/images/training/lessons/1-copy.jpg', 'images/training/lessons/1-copy.jpg'),
    array('/images/training/lessons/1.jpg', 'images/training/lessons/1.jpg'),
    array('/images/training/lessons/10-160px.jpg', 'images/training/lessons/10-160px.jpg'),
    array('/images/training/lessons/10.jpg', 'images/training/lessons/10.jpg'),
    array('/images/training/lessons/2-160px.jpg', 'images/training/lessons/2-160px.jpg'),
    array('/images/training/lessons/2.jpg', 'images/training/lessons/2.jpg'),
    array('/images/training/lessons/3-160px.jpg', 'images/training/lessons/3-160px.jpg'),
    array('/images/training/lessons/3-copy-160px.jpg', 'images/training/lessons/3-copy-160px.jpg'),
    array('/images/training/lessons/3-copy.jpg', 'images/training/lessons/3-copy.jpg'),
    array('/images/training/lessons/3.jpg', 'images/training/lessons/3.jpg'),
    array('/images/training/lessons/4-160px.jpg', 'images/training/lessons/4-160px.jpg'),
    array('/images/training/lessons/4-copy-160px.jpg', 'images/training/lessons/4-copy-160px.jpg'),
    array('/images/training/lessons/4-copy.jpg', 'images/training/lessons/4-copy.jpg'),
    array('/images/training/lessons/4.jpg', 'images/training/lessons/4.jpg'),
    array('/images/training/lessons/5-160px.jpg', 'images/training/lessons/5-160px.jpg'),
    array('/images/training/lessons/5-copy-160px.jpg', 'images/training/lessons/5-copy-160px.jpg'),
    array('/images/training/lessons/5-copy.jpg', 'images/training/lessons/5-copy.jpg'),
    array('/images/training/lessons/5.jpg', 'images/training/lessons/5.jpg'),
    array('/images/training/lessons/53ee0b36390985393dc0042602fc540d-160px.jpg', 'images/training/lessons/53ee0b36390985393dc0042602fc540d-160px.jpg'),
    array('/images/training/lessons/53ee0b36390985393dc0042602fc540d.jpg', 'images/training/lessons/53ee0b36390985393dc0042602fc540d.jpg'),
    array('/images/training/lessons/6-160px.jpg', 'images/training/lessons/6-160px.jpg'),
    array('/images/training/lessons/6-copy-160px.jpg', 'images/training/lessons/6-copy-160px.jpg'),
    array('/images/training/lessons/6-copy.jpg', 'images/training/lessons/6-copy.jpg'),
    array('/images/training/lessons/6.jpg', 'images/training/lessons/6.jpg'),
    array('/images/training/lessons/7-160px.jpg', 'images/training/lessons/7-160px.jpg'),
    array('/images/training/lessons/7-copy-160px.jpg', 'images/training/lessons/7-copy-160px.jpg'),
    array('/images/training/lessons/7-copy.jpg', 'images/training/lessons/7-copy.jpg'),
    array('/images/training/lessons/7.jpg', 'images/training/lessons/7.jpg'),
    array('/images/training/lessons/8-160px.jpg', 'images/training/lessons/8-160px.jpg'),
    array('/images/training/lessons/8-copy-160px.jpg', 'images/training/lessons/8-copy-160px.jpg'),
    array('/images/training/lessons/8-copy.jpg', 'images/training/lessons/8-copy.jpg'),
    array('/images/training/lessons/8.jpg', 'images/training/lessons/8.jpg'),
    array('/images/training/lessons/9-160px.jpg', 'images/training/lessons/9-160px.jpg'),
    array('/images/training/lessons/9.jpg', 'images/training/lessons/9.jpg'),
    array('/images/training/lessons/bike-160px.jpg', 'images/training/lessons/bike-160px.jpg'),
    array('/images/training/lessons/bike.jpg', 'images/training/lessons/bike.jpg'),
    array('/images/training/lessons/bike1-160px.jpg', 'images/training/lessons/bike1-160px.jpg'),
    array('/images/training/lessons/bike1.jpg', 'images/training/lessons/bike1.jpg'),
    array('/images/training/lessons/fd30b53dec9382cac84216c7936d2831-160px.png', 'images/training/lessons/fd30b53dec9382cac84216c7936d2831-160px.png'),
    array('/images/training/lessons/fd30b53dec9382cac84216c7936d2831.png', 'images/training/lessons/fd30b53dec9382cac84216c7936d2831.png'),
    array('/images/training/lessons/gadjet1-160px.jpg', 'images/training/lessons/gadjet1-160px.jpg'),
    array('/images/training/lessons/gadjet1.jpg', 'images/training/lessons/gadjet1.jpg'),
    array('/images/training/lessons/gadjet2-160px.jpg', 'images/training/lessons/gadjet2-160px.jpg'),
    array('/images/training/lessons/gadjet2.jpg', 'images/training/lessons/gadjet2.jpg'),
    array('/images/training/lessons/gidro-160px.jpg', 'images/training/lessons/gidro-160px.jpg'),
    array('/images/training/lessons/gidro-copy-160px.jpg', 'images/training/lessons/gidro-copy-160px.jpg'),
    array('/images/training/lessons/gidro-copy.jpg', 'images/training/lessons/gidro-copy.jpg'),
    array('/images/training/lessons/gidro.jpg', 'images/training/lessons/gidro.jpg'),
    array('/images/training/lessons/gidro2-160px.jpg', 'images/training/lessons/gidro2-160px.jpg'),
    array('/images/training/lessons/gidro2.jpg', 'images/training/lessons/gidro2.jpg'),
    array('/images/training/lessons/gidro3-160px.jpg', 'images/training/lessons/gidro3-160px.jpg'),
    array('/images/training/lessons/gidro3.jpg', 'images/training/lessons/gidro3.jpg'),
    array('/images/training/lessons/giro-160px.jpg', 'images/training/lessons/giro-160px.jpg'),
    array('/images/training/lessons/giro.jpg', 'images/training/lessons/giro.jpg'),
    array('/images/training/lessons/habitstri-160px.jpg', 'images/training/lessons/habitstri-160px.jpg'),
    array('/images/training/lessons/habitstri-copy-160px.jpg', 'images/training/lessons/habitstri-copy-160px.jpg'),
    array('/images/training/lessons/habitstri-copy.jpg', 'images/training/lessons/habitstri-copy.jpg'),
    array('/images/training/lessons/habitstri.jpg', 'images/training/lessons/habitstri.jpg'),
    array('/images/training/lessons/howtri-160px.jpg', 'images/training/lessons/howtri-160px.jpg'),
    array('/images/training/lessons/howtri.jpg', 'images/training/lessons/howtri.jpg'),
    array('/images/training/lessons/morningtri-160px.jpg', 'images/training/lessons/morningtri-160px.jpg'),
    array('/images/training/lessons/morningtri.jpg', 'images/training/lessons/morningtri.jpg'),
    array('/images/training/lessons/motivation1-160px.jpg', 'images/training/lessons/motivation1-160px.jpg'),
    array('/images/training/lessons/motivation1.jpg', 'images/training/lessons/motivation1.jpg'),
    array('/images/training/lessons/run1-160px.jpg', 'images/training/lessons/run1-160px.jpg'),
    array('/images/training/lessons/run1.jpg', 'images/training/lessons/run1.jpg'),
    array('/images/training/lessons/runcross-160px.jpg', 'images/training/lessons/runcross-160px.jpg'),
    array('/images/training/lessons/runcross.jpg', 'images/training/lessons/runcross.jpg'),
    array('/images/training/lessons/soft-160px.jpg', 'images/training/lessons/soft-160px.jpg'),
    array('/images/training/lessons/soft.jpg', 'images/training/lessons/soft.jpg'),
    array('/images/training/lessons/swim1-160px.jpg', 'images/training/lessons/swim1-160px.jpg'),
    array('/images/training/lessons/swim1.jpg', 'images/training/lessons/swim1.jpg'),
    array('/images/training/lessons/training1.jpg', 'images/training/lessons/training1.jpg'),
    array('/images/training/lessons/training10.jpg', 'images/training/lessons/training10.jpg'),
    array('/images/training/lessons/training11.jpg', 'images/training/lessons/training11.jpg'),
    array('/images/training/lessons/training2.jpg', 'images/training/lessons/training2.jpg'),
    array('/images/training/lessons/training3.jpg', 'images/training/lessons/training3.jpg'),
    array('/images/training/lessons/training4.jpg', 'images/training/lessons/training4.jpg'),
    array('/images/training/lessons/training5.jpg', 'images/training/lessons/training5.jpg'),
    array('/images/training/lessons/training6.jpg', 'images/training/lessons/training6.jpg'),
    array('/images/training/lessons/training7.jpg', 'images/training/lessons/training7.jpg'),
    array('/images/training/lessons/training8.jpg', 'images/training/lessons/training8.jpg'),
    array('/images/training/lessons/training9.jpg', 'images/training/lessons/training9.jpg'),
    array('/images/training/run-copy.jpg', 'images/training/run-copy.jpg'),
    array('/images/training/run.jpg', 'images/training/run.jpg'),
    array('/images/training/school11.jpg', 'images/training/school11.jpg'),
    array('/images/training/sections/Group915-copy.jpg', 'images/training/sections/Group915-copy.jpg'),
    array('/images/training/sections/Group915.jpg', 'images/training/sections/Group915.jpg'),
    array('/images/training/sections/swim (1).jpg', 'images/training/sections/swim (1).jpg'),
    array('/images/training/sections/swim (2).jpg', 'images/training/sections/swim (2).jpg'),
    array('/images/training/sections/swim (3)-copy.jpg', 'images/training/sections/swim (3)-copy.jpg'),
    array('/images/training/sections/swim (3).jpg', 'images/training/sections/swim (3).jpg'),
    array('/images/training/sections/swim.jpg', 'images/training/sections/swim.jpg'),
    array('/images/training/smcourse-copy.jpg', 'images/training/smcourse-copy.jpg'),
    array('/images/training/smcourse.jpg', 'images/training/smcourse.jpg'),
    array('/images/training/swim-copy.jpg', 'images/training/swim-copy.jpg'),
    array('/images/training/swim.jpg', 'images/training/swim.jpg'),
    array('/images/training/tri.jpg', 'images/training/tri.jpg'),
    array('/images/training/tri2.jpg', 'images/training/tri2.jpg'),
    array('/images/training2.jpg', 'images/training2.jpg'),
    array('/load/hometask/lessons/20/user/77727b7e05fb7eb06316df80598d478d.png', 'load/hometask/lessons/20/user/77727b7e05fb7eb06316df80598d478d.png'),
    array('/load/thumbs/16478 [преобразованный].png', 'load/thumbs/16478 [преобразованный].png'),
    array('/load/thumbs/3 (1).jpg', 'load/thumbs/3 (1).jpg'),
    array('/load/thumbs/773657_37780-Sarah1-e1555765907998.jpg', 'load/thumbs/773657_37780-Sarah1-e1555765907998.jpg'),
    array('/load/thumbs/Screenshot_20200220-013947_AliRadar.jpg', 'load/thumbs/Screenshot_20200220-013947_AliRadar.jpg'),
    array('/load/thumbs/aleksandr (1).png', 'load/thumbs/aleksandr (1).png'),
    array('/load/thumbs/alexandrkurteev_2.png', 'load/thumbs/alexandrkurteev_2.png'),
    array('/load/thumbs/blog-hero.jpg', 'load/thumbs/blog-hero.jpg'),
    array('/load/thumbs/cheboksar.jpg', 'load/thumbs/cheboksar.jpg'),
    array('/load/thumbs/course/1k.jpg', 'load/thumbs/course/1k.jpg'),
    array('/load/thumbs/course/2k.jpg', 'load/thumbs/course/2k.jpg'),
    array('/load/thumbs/course/3k.jpg', 'load/thumbs/course/3k.jpg'),
    array('/load/thumbs/course/54.jpg', 'load/thumbs/course/54.jpg'),
    array('/load/thumbs/course/Kak-nachat-begat-polnoe-rukovodstvo-dlya-novichkov_1579903200-1140x570.jpg', 'load/thumbs/course/Kak-nachat-begat-polnoe-rukovodstvo-dlya-novichkov_1579903200-1140x570.jpg'),
    array('/load/thumbs/course/category/1.jpg', 'load/thumbs/course/category/1.jpg'),
    array('/load/thumbs/course/category/Razminka-pered-begom.jpg', 'load/thumbs/course/category/Razminka-pered-begom.jpg'),
    array('/load/thumbs/course/category/bonusesmain.jpg', 'load/thumbs/course/category/bonusesmain.jpg'),
    array('/load/thumbs/course/category/course.jpg', 'load/thumbs/course/category/course.jpg'),
    array('/load/thumbs/course/lessonsystem (1).jpg', 'load/thumbs/course/lessonsystem (1).jpg'),
    array('/load/thumbs/course/triatlon.jpg', 'load/thumbs/course/triatlon.jpg'),
    array('/load/thumbs/course/triatlon1.jpg', 'load/thumbs/course/triatlon1.jpg'),
    array('/load/thumbs/down-arrow (1).png', 'load/thumbs/down-arrow (1).png'),
    array('/load/thumbs/down-arrow.png', 'load/thumbs/down-arrow.png'),
    array('/load/thumbs/downloadfile.png', 'load/thumbs/downloadfile.png'),
    array('/load/thumbs/forvideo/integration.jpg', 'load/thumbs/forvideo/integration.jpg'),
    array('/load/thumbs/forvideo/intro1.jpg', 'load/thumbs/forvideo/intro1.jpg'),
    array('/load/thumbs/forvideo/intro2.jpg', 'load/thumbs/forvideo/intro2.jpg'),
    array('/load/thumbs/forvideo/intro3.jpg', 'load/thumbs/forvideo/intro3.jpg'),
    array('/load/thumbs/forvideo/intro5.jpg', 'load/thumbs/forvideo/intro5.jpg'),
    array('/load/thumbs/forvideo/membership1-1.jpg', 'load/thumbs/forvideo/membership1-1.jpg'),
    array('/load/thumbs/forvideo/membership1.jpg', 'load/thumbs/forvideo/membership1.jpg'),
    array('/load/thumbs/forvideo/membership2.jpg', 'load/thumbs/forvideo/membership2.jpg'),
    array('/load/thumbs/forvideo/membership3.jpg', 'load/thumbs/forvideo/membership3.jpg'),
    array('/load/thumbs/forvideo/membership4.jpg', 'load/thumbs/forvideo/membership4.jpg'),
    array('/load/thumbs/forvideo/membership5.jpg', 'load/thumbs/forvideo/membership5.jpg'),
    array('/load/thumbs/forvideo/partner1-1.jpg', 'load/thumbs/forvideo/partner1-1.jpg'),
    array('/load/thumbs/forvideo/partner1.jpg', 'load/thumbs/forvideo/partner1.jpg'),
    array('/load/thumbs/forvideo/partner2.jpg', 'load/thumbs/forvideo/partner2.jpg'),
    array('/load/thumbs/forvideo/partner3.jpg', 'load/thumbs/forvideo/partner3.jpg'),
    array('/load/thumbs/forvideo/partner4.jpg', 'load/thumbs/forvideo/partner4.jpg'),
    array('/load/thumbs/forvideo/partner5.jpg', 'load/thumbs/forvideo/partner5.jpg'),
    array('/load/thumbs/forvideo/sale1.jpg', 'load/thumbs/forvideo/sale1.jpg'),
    array('/load/thumbs/forvideo/sale2.jpg', 'load/thumbs/forvideo/sale2.jpg'),
    array('/load/thumbs/forvideo/sale3.jpg', 'load/thumbs/forvideo/sale3.jpg'),
    array('/load/thumbs/forvideo/sale4.jpg', 'load/thumbs/forvideo/sale4.jpg'),
    array('/load/thumbs/forvideo/sale5.jpg', 'load/thumbs/forvideo/sale5.jpg'),
    array('/load/thumbs/forvideo/sale6.jpg', 'load/thumbs/forvideo/sale6.jpg'),
    array('/load/thumbs/forvideo/sale7.jpg', 'load/thumbs/forvideo/sale7.jpg'),
    array('/load/thumbs/forvideo/site1.jpg', 'load/thumbs/forvideo/site1.jpg'),
    array('/load/thumbs/forvideo/site10.jpg', 'load/thumbs/forvideo/site10.jpg'),
    array('/load/thumbs/forvideo/site2.jpg', 'load/thumbs/forvideo/site2.jpg'),
    array('/load/thumbs/forvideo/site3.jpg', 'load/thumbs/forvideo/site3.jpg'),
    array('/load/thumbs/forvideo/site4.jpg', 'load/thumbs/forvideo/site4.jpg'),
    array('/load/thumbs/forvideo/site5.jpg', 'load/thumbs/forvideo/site5.jpg'),
    array('/load/thumbs/forvideo/site6.jpg', 'load/thumbs/forvideo/site6.jpg'),
    array('/load/thumbs/forvideo/site7.jpg', 'load/thumbs/forvideo/site7.jpg'),
    array('/load/thumbs/forvideo/site8.jpg', 'load/thumbs/forvideo/site8.jpg'),
    array('/load/thumbs/forvideo/site9.jpg', 'load/thumbs/forvideo/site9.jpg'),
    array('/load/thumbs/forvideo/user1.jpg', 'load/thumbs/forvideo/user1.jpg'),
    array('/load/thumbs/forvideo/user2.jpg', 'load/thumbs/forvideo/user2.jpg'),
    array('/load/thumbs/forvideo/user3.jpg', 'load/thumbs/forvideo/user3.jpg'),
    array('/load/thumbs/forvideo/user4.jpg', 'load/thumbs/forvideo/user4.jpg'),
    array('/load/thumbs/forvideo/user5.jpg', 'load/thumbs/forvideo/user5.jpg'),
    array('/load/thumbs/hero (1).jpg', 'load/thumbs/hero (1).jpg'),
    array('/load/thumbs/hero.jpg', 'load/thumbs/hero.jpg'),
    array('/load/thumbs/keit.jpg', 'load/thumbs/keit.jpg'),
    array('/load/thumbs/lessons/1-1.jpg', 'load/thumbs/lessons/1-1.jpg'),
    array('/load/thumbs/lessons/1.jpg', 'load/thumbs/lessons/1.jpg'),
    array('/load/thumbs/lessons/10.jpg', 'load/thumbs/lessons/10.jpg'),
    array('/load/thumbs/lessons/11.jpg', 'load/thumbs/lessons/11.jpg'),
    array('/load/thumbs/lessons/1l.jpg', 'load/thumbs/lessons/1l.jpg'),
    array('/load/thumbs/lessons/2.jpg', 'load/thumbs/lessons/2.jpg'),
    array('/load/thumbs/lessons/3.jpg', 'load/thumbs/lessons/3.jpg'),
    array('/load/thumbs/lessons/4.jpg', 'load/thumbs/lessons/4.jpg'),
    array('/load/thumbs/lessons/5.jpg', 'load/thumbs/lessons/5.jpg'),
    array('/load/thumbs/lessons/6.jpg', 'load/thumbs/lessons/6.jpg'),
    array('/load/thumbs/lessons/7.jpg', 'load/thumbs/lessons/7.jpg'),
    array('/load/thumbs/lessons/8.jpg', 'load/thumbs/lessons/8.jpg'),
    array('/load/thumbs/lessons/9.jpg', 'load/thumbs/lessons/9.jpg'),
    array('/load/thumbs/lessons/j3-detail.png', 'load/thumbs/lessons/j3-detail.png'),
    array('/load/thumbs/lessons/kirov.jpg', 'load/thumbs/lessons/kirov.jpg'),
    array('/load/thumbs/lessons/kurs-2.jpg', 'load/thumbs/lessons/kurs-2.jpg'),
    array('/load/thumbs/lessons/motivation.jpg', 'load/thumbs/lessons/motivation.jpg'),
    array('/load/thumbs/lessons/runner.jpg', 'load/thumbs/lessons/runner.jpg'),
    array('/load/thumbs/lessons/swim.jpg', 'load/thumbs/lessons/swim.jpg'),
    array('/load/thumbs/lessons/velosiped.jpg', 'load/thumbs/lessons/velosiped.jpg'),
    array('/load/thumbs/lessons/yoshka.jpg', 'load/thumbs/lessons/yoshka.jpg'),
    array('/load/thumbs/logo-maraphonec-copy.png', 'load/thumbs/logo-maraphonec-copy.png'),
    array('/load/thumbs/logo-maraphonec.png', 'load/thumbs/logo-maraphonec.png'),
    array('/load/thumbs/logo-sport.png', 'load/thumbs/logo-sport.png'),
    array('/load/thumbs/logo2.png', 'load/thumbs/logo2.png'),
    array('/load/thumbs/logo3.png', 'load/thumbs/logo3.png'),
    array('/load/thumbs/morning.jpg', 'load/thumbs/morning.jpg'),
    array('/load/thumbs/olega.png', 'load/thumbs/olega.png'),
    array('/load/thumbs/post-002.png', 'load/thumbs/post-002.png'),
    array('/load/thumbs/product/108411307_w640_h640_turnik-atlet-3[1].jpg', 'load/thumbs/product/108411307_w640_h640_turnik-atlet-3[1].jpg'),
    array('/load/thumbs/product/1k.jpg', 'load/thumbs/product/1k.jpg'),
    array('/load/thumbs/product/3k.jpg', 'load/thumbs/product/3k.jpg'),
    array('/load/thumbs/product/90.jpg', 'load/thumbs/product/90.jpg'),
    array('/load/thumbs/product/bike.jpg', 'load/thumbs/product/bike.jpg'),
    array('/load/thumbs/product/couch.png', 'load/thumbs/product/couch.png'),
    array('/load/thumbs/product/maraphon.jpg', 'load/thumbs/product/maraphon.jpg'),
    array('/load/thumbs/product/nike.jpg', 'load/thumbs/product/nike.jpg'),
    array('/load/thumbs/product/product-marafon.jpg', 'load/thumbs/product/product-marafon.jpg'),
    array('/load/thumbs/product/stand.jpg', 'load/thumbs/product/stand.jpg'),
    array('/load/thumbs/product/startrun.jpg', 'load/thumbs/product/startrun.jpg'),
    array('/load/thumbs/product/swim.jpg', 'load/thumbs/product/swim.jpg'),
    array('/load/thumbs/product/tri2.jpg', 'load/thumbs/product/tri2.jpg'),
    array('/load/thumbs/product/triathlonpremium.png', 'load/thumbs/product/triathlonpremium.png'),
    array('/load/thumbs/product/triathlonstand.png', 'load/thumbs/product/triathlonstand.png'),
    array('/load/thumbs/product/triatlon-product.jpg', 'load/thumbs/product/triatlon-product.jpg'),
    array('/load/thumbs/product/tristand.png', 'load/thumbs/product/tristand.png'),
    array('/load/thumbs/product/vip.png', 'load/thumbs/product/vip.png'),
    array('/load/thumbs/product/vip2-copy.png', 'load/thumbs/product/vip2-copy.png'),
    array('/load/thumbs/product/vip2.png', 'load/thumbs/product/vip2.png'),
    array('/load/thumbs/socicons/facebook.png', 'load/thumbs/socicons/facebook.png'),
    array('/load/thumbs/socicons/instagram.png', 'load/thumbs/socicons/instagram.png'),
    array('/load/thumbs/socicons/telegram.png', 'load/thumbs/socicons/telegram.png'),
    array('/load/thumbs/socicons/vk 1.png', 'load/thumbs/socicons/vk 1.png'),
    array('/load/thumbs/streaks.png', 'load/thumbs/streaks.png'),
    array('/load/thumbs/telegram.png', 'load/thumbs/telegram.png'),
    array('/load/thumbs/thumbs/23-Defenders_Day-23.jpg', 'load/thumbs/thumbs/23-Defenders_Day-23.jpg'),
    array('/load/thumbs/thumbs/Logosports.png', 'load/thumbs/thumbs/Logosports.png'),
    array('/load/thumbs/thumbs/Screenshot_20200220-013947_AliRadar.jpg', 'load/thumbs/thumbs/Screenshot_20200220-013947_AliRadar.jpg'),
    array('/load/thumbs/thumbs/Shika.png', 'load/thumbs/thumbs/Shika.png'),
    array('/load/thumbs/thumbs/aleksandr (1).png', 'load/thumbs/thumbs/aleksandr (1).png'),
    array('/load/thumbs/thumbs/alexandrkurteev_2.png', 'load/thumbs/thumbs/alexandrkurteev_2.png'),
    array('/load/thumbs/thumbs/blog-hero.jpg', 'load/thumbs/thumbs/blog-hero.jpg'),
    array('/load/thumbs/thumbs/cheboksar.jpg', 'load/thumbs/thumbs/cheboksar.jpg'),
    array('/load/thumbs/thumbs/female_avatar.png', 'load/thumbs/thumbs/female_avatar.png'),
    array('/load/thumbs/thumbs/hero (1).jpg', 'load/thumbs/thumbs/hero (1).jpg'),
    array('/load/thumbs/thumbs/hero.jpg', 'load/thumbs/thumbs/hero.jpg'),
    array('/load/thumbs/thumbs/hero1.jpg', 'load/thumbs/thumbs/hero1.jpg'),
    array('/load/thumbs/thumbs/keit.jpg', 'load/thumbs/thumbs/keit.jpg'),
    array('/load/thumbs/thumbs/logo-sport.png', 'load/thumbs/thumbs/logo-sport.png'),
    array('/load/thumbs/thumbs/logo2.png', 'load/thumbs/thumbs/logo2.png'),
    array('/load/thumbs/thumbs/logo3.png', 'load/thumbs/thumbs/logo3.png'),
    array('/load/thumbs/thumbs/noavatar.png', 'load/thumbs/thumbs/noavatar.png'),
    array('/load/thumbs/thumbs/olega.png', 'load/thumbs/thumbs/olega.png'),
    array('/load/thumbs/thumbs/pavel.jpg', 'load/thumbs/thumbs/pavel.jpg'),
    array('/load/thumbs/thumbs/post-002.png', 'load/thumbs/thumbs/post-002.png'),
    array('/load/thumbs/thumbs/sila_metoda.jpg', 'load/thumbs/thumbs/sila_metoda.jpg'),
    array('/load/thumbs/thumbs/tema-T¦м¬о-э-л·.jpg', 'load/thumbs/thumbs/tema-T¦м¬о-э-л·.jpg'),
    array('/load/thumbs/thumbs/tr.jpg', 'load/thumbs/thumbs/tr.jpg'),
    array('/load/thumbs/thumbs/witcher.jpg', 'load/thumbs/thumbs/witcher.jpg'),
    array('/load/thumbs/tracker.png', 'load/thumbs/tracker.png'),
    array('/load/thumbs/training/IM-smart-programs-header.jpg', 'load/thumbs/training/IM-smart-programs-header.jpg'),
    array('/load/thumbs/training/bike.jpg', 'load/thumbs/training/bike.jpg'),
    array('/load/thumbs/training/lessons/1-160px.jpg', 'load/thumbs/training/lessons/1-160px.jpg'),
    array('/load/thumbs/training/lessons/1-2-160px.jpg', 'load/thumbs/training/lessons/1-2-160px.jpg'),
    array('/load/thumbs/training/lessons/1-2.jpg', 'load/thumbs/training/lessons/1-2.jpg'),
    array('/load/thumbs/training/lessons/1-copy-160px.jpg', 'load/thumbs/training/lessons/1-copy-160px.jpg'),
    array('/load/thumbs/training/lessons/1-copy.jpg', 'load/thumbs/training/lessons/1-copy.jpg'),
    array('/load/thumbs/training/lessons/1.jpg', 'load/thumbs/training/lessons/1.jpg'),
    array('/load/thumbs/training/lessons/10-160px.jpg', 'load/thumbs/training/lessons/10-160px.jpg'),
    array('/load/thumbs/training/lessons/10.jpg', 'load/thumbs/training/lessons/10.jpg'),
    array('/load/thumbs/training/lessons/2-160px.jpg', 'load/thumbs/training/lessons/2-160px.jpg'),
    array('/load/thumbs/training/lessons/2.jpg', 'load/thumbs/training/lessons/2.jpg'),
    array('/load/thumbs/training/lessons/3-160px.jpg', 'load/thumbs/training/lessons/3-160px.jpg'),
    array('/load/thumbs/training/lessons/3.jpg', 'load/thumbs/training/lessons/3.jpg'),
    array('/load/thumbs/training/lessons/4-160px.jpg', 'load/thumbs/training/lessons/4-160px.jpg'),
    array('/load/thumbs/training/lessons/4.jpg', 'load/thumbs/training/lessons/4.jpg'),
    array('/load/thumbs/training/lessons/5-160px.jpg', 'load/thumbs/training/lessons/5-160px.jpg'),
    array('/load/thumbs/training/lessons/5.jpg', 'load/thumbs/training/lessons/5.jpg'),
    array('/load/thumbs/training/lessons/53ee0b36390985393dc0042602fc540d-160px.jpg', 'load/thumbs/training/lessons/53ee0b36390985393dc0042602fc540d-160px.jpg'),
    array('/load/thumbs/training/lessons/53ee0b36390985393dc0042602fc540d.jpg', 'load/thumbs/training/lessons/53ee0b36390985393dc0042602fc540d.jpg'),
    array('/load/thumbs/training/lessons/6-160px.jpg', 'load/thumbs/training/lessons/6-160px.jpg'),
    array('/load/thumbs/training/lessons/6.jpg', 'load/thumbs/training/lessons/6.jpg'),
    array('/load/thumbs/training/lessons/7-160px.jpg', 'load/thumbs/training/lessons/7-160px.jpg'),
    array('/load/thumbs/training/lessons/7.jpg', 'load/thumbs/training/lessons/7.jpg'),
    array('/load/thumbs/training/lessons/8-160px.jpg', 'load/thumbs/training/lessons/8-160px.jpg'),
    array('/load/thumbs/training/lessons/8.jpg', 'load/thumbs/training/lessons/8.jpg'),
    array('/load/thumbs/training/lessons/9-160px.jpg', 'load/thumbs/training/lessons/9-160px.jpg'),
    array('/load/thumbs/training/lessons/9.jpg', 'load/thumbs/training/lessons/9.jpg'),
    array('/load/thumbs/training/lessons/bike-160px.jpg', 'load/thumbs/training/lessons/bike-160px.jpg'),
    array('/load/thumbs/training/lessons/bike.jpg', 'load/thumbs/training/lessons/bike.jpg'),
    array('/load/thumbs/training/lessons/bike1-160px.jpg', 'load/thumbs/training/lessons/bike1-160px.jpg'),
    array('/load/thumbs/training/lessons/bike1.jpg', 'load/thumbs/training/lessons/bike1.jpg'),
    array('/load/thumbs/training/lessons/fd30b53dec9382cac84216c7936d2831-160px.png', 'load/thumbs/training/lessons/fd30b53dec9382cac84216c7936d2831-160px.png'),
    array('/load/thumbs/training/lessons/fd30b53dec9382cac84216c7936d2831.png', 'load/thumbs/training/lessons/fd30b53dec9382cac84216c7936d2831.png'),
    array('/load/thumbs/training/lessons/gadjet1-160px.jpg', 'load/thumbs/training/lessons/gadjet1-160px.jpg'),
    array('/load/thumbs/training/lessons/gadjet1.jpg', 'load/thumbs/training/lessons/gadjet1.jpg'),
    array('/load/thumbs/training/lessons/gadjet2-160px.jpg', 'load/thumbs/training/lessons/gadjet2-160px.jpg'),
    array('/load/thumbs/training/lessons/gadjet2.jpg', 'load/thumbs/training/lessons/gadjet2.jpg'),
    array('/load/thumbs/training/lessons/gidro-160px.jpg', 'load/thumbs/training/lessons/gidro-160px.jpg'),
    array('/load/thumbs/training/lessons/gidro-copy-160px.jpg', 'load/thumbs/training/lessons/gidro-copy-160px.jpg'),
    array('/load/thumbs/training/lessons/gidro-copy.jpg', 'load/thumbs/training/lessons/gidro-copy.jpg'),
    array('/load/thumbs/training/lessons/gidro.jpg', 'load/thumbs/training/lessons/gidro.jpg'),
    array('/load/thumbs/training/lessons/gidro2-160px.jpg', 'load/thumbs/training/lessons/gidro2-160px.jpg'),
    array('/load/thumbs/training/lessons/gidro2.jpg', 'load/thumbs/training/lessons/gidro2.jpg'),
    array('/load/thumbs/training/lessons/gidro3-160px.jpg', 'load/thumbs/training/lessons/gidro3-160px.jpg'),
    array('/load/thumbs/training/lessons/gidro3.jpg', 'load/thumbs/training/lessons/gidro3.jpg'),
    array('/load/thumbs/training/lessons/giro-160px.jpg', 'load/thumbs/training/lessons/giro-160px.jpg'),
    array('/load/thumbs/training/lessons/giro.jpg', 'load/thumbs/training/lessons/giro.jpg'),
    array('/load/thumbs/training/lessons/habitstri-160px.jpg', 'load/thumbs/training/lessons/habitstri-160px.jpg'),
    array('/load/thumbs/training/lessons/habitstri-copy-160px.jpg', 'load/thumbs/training/lessons/habitstri-copy-160px.jpg'),
    array('/load/thumbs/training/lessons/habitstri-copy.jpg', 'load/thumbs/training/lessons/habitstri-copy.jpg'),
    array('/load/thumbs/training/lessons/habitstri.jpg', 'load/thumbs/training/lessons/habitstri.jpg'),
    array('/load/thumbs/training/lessons/howtri-160px.jpg', 'load/thumbs/training/lessons/howtri-160px.jpg'),
    array('/load/thumbs/training/lessons/howtri.jpg', 'load/thumbs/training/lessons/howtri.jpg'),
    array('/load/thumbs/training/lessons/morningtri-160px.jpg', 'load/thumbs/training/lessons/morningtri-160px.jpg'),
    array('/load/thumbs/training/lessons/morningtri.jpg', 'load/thumbs/training/lessons/morningtri.jpg'),
    array('/load/thumbs/training/lessons/motivation1-160px.jpg', 'load/thumbs/training/lessons/motivation1-160px.jpg'),
    array('/load/thumbs/training/lessons/motivation1.jpg', 'load/thumbs/training/lessons/motivation1.jpg'),
    array('/load/thumbs/training/lessons/run1-160px.jpg', 'load/thumbs/training/lessons/run1-160px.jpg'),
    array('/load/thumbs/training/lessons/run1.jpg', 'load/thumbs/training/lessons/run1.jpg'),
    array('/load/thumbs/training/lessons/runcross-160px.jpg', 'load/thumbs/training/lessons/runcross-160px.jpg'),
    array('/load/thumbs/training/lessons/runcross.jpg', 'load/thumbs/training/lessons/runcross.jpg'),
    array('/load/thumbs/training/lessons/soft-160px.jpg', 'load/thumbs/training/lessons/soft-160px.jpg'),
    array('/load/thumbs/training/lessons/soft.jpg', 'load/thumbs/training/lessons/soft.jpg'),
    array('/load/thumbs/training/lessons/swim1-160px.jpg', 'load/thumbs/training/lessons/swim1-160px.jpg'),
    array('/load/thumbs/training/lessons/swim1.jpg', 'load/thumbs/training/lessons/swim1.jpg'),
    array('/load/thumbs/training/lessons/training1.jpg', 'load/thumbs/training/lessons/training1.jpg'),
    array('/load/thumbs/training/lessons/training10.jpg', 'load/thumbs/training/lessons/training10.jpg'),
    array('/load/thumbs/training/lessons/training11.jpg', 'load/thumbs/training/lessons/training11.jpg'),
    array('/load/thumbs/training/lessons/training2.jpg', 'load/thumbs/training/lessons/training2.jpg'),
    array('/load/thumbs/training/lessons/training3.jpg', 'load/thumbs/training/lessons/training3.jpg'),
    array('/load/thumbs/training/lessons/training4.jpg', 'load/thumbs/training/lessons/training4.jpg'),
    array('/load/thumbs/training/lessons/training5.jpg', 'load/thumbs/training/lessons/training5.jpg'),
    array('/load/thumbs/training/lessons/training6.jpg', 'load/thumbs/training/lessons/training6.jpg'),
    array('/load/thumbs/training/lessons/training7.jpg', 'load/thumbs/training/lessons/training7.jpg'),
    array('/load/thumbs/training/lessons/training8.jpg', 'load/thumbs/training/lessons/training8.jpg'),
    array('/load/thumbs/training/lessons/training9.jpg', 'load/thumbs/training/lessons/training9.jpg'),
    array('/load/thumbs/training/run-copy.jpg', 'load/thumbs/training/run-copy.jpg'),
    array('/load/thumbs/training/run.jpg', 'load/thumbs/training/run.jpg'),
    array('/load/thumbs/training/school11.jpg', 'load/thumbs/training/school11.jpg'),
    array('/load/thumbs/training/smcourse-copy.jpg', 'load/thumbs/training/smcourse-copy.jpg'),
    array('/load/thumbs/training/smcourse.jpg', 'load/thumbs/training/smcourse.jpg'),
    array('/load/thumbs/training/swim-copy.jpg', 'load/thumbs/training/swim-copy.jpg'),
    array('/load/thumbs/training/swim.jpg', 'load/thumbs/training/swim.jpg'),
    array('/load/thumbs/training/tri.jpg', 'load/thumbs/training/tri.jpg'),
    array('/load/thumbs/training/tri2.jpg', 'load/thumbs/training/tri2.jpg'),
    array('/load/thumbs/training2.jpg', 'load/thumbs/training2.jpg'),
    array('/load/training/lessons/21/tracker365.pdf', 'load/training/lessons/21/tracker365.pdf'),
    array('/load/training/lessons/34/старая   -бумага  _   100 (1).jpg', 'load/training/lessons/34/старая   -бумага  _   100 (1).jpg'),
    array('/load/training/lessons/36/training.jpg', 'load/training/lessons/36/training.jpg'),
    array('/load/training/lessons/43/tracker365.pdf', 'load/training/lessons/43/tracker365.pdf'),
    array('/template/admin/images/ext/forum.svg', 'template/admin/images/ext/forum.svg'),
    array('/template/admin/images/payments/company.png', 'template/admin/images/payments/company.png'),
    array('/template/admin/images/payments/custom.png', 'template/admin/images/payments/custom.png'),
    array('/template/admin/images/payments/paypal.png', 'template/admin/images/payments/paypal.png'),
    array('/template/admin/images/payments/robokassa.png', 'template/admin/images/payments/robokassa.png'),
    array('/template/admin/images/payments/yakassa.png', 'template/admin/images/payments/yakassa.png'),
    array('/template/admin/images/payments/yakassa2.png', 'template/admin/images/payments/yakassa2.png'),
);?>